### ISSUE TITLE
list of necessary go tools

### ISSUE THREAD

**Issue by selvik** [fatih/vim-go-tutorial#27]
Hi,

I am following the tutorial to set up vim-go. There is a specific line:
"And finally be sure to install all necessary Go tools (such as guru, goimports, gocode, etc...)".
Is there a list somewhere of what all these tools are ? Even a short tool of the most commonly used ones would be very helpful.

Thanks for a great tool!

**Comment by superwhykz** [comment]
I do not think so. You just need to search  https://godoc.org/

**Comment by fatih** [comment]
@selvik if you follow the tutorial, it says you should run `:GoInstallBinaries`. That command all tools. Also the tutorial explains all tools one by one. Thanks.
