### ISSUE TITLE
Windows instructions needed

### ISSUE THREAD

**Issue by carlca** [fatih/vim-go-tutorial#30]
Hello, it would be very handy to have Windows instructions, specifically ones which deal with the differences in the way _vimrc is handled. I've edited my _vimrc file so that the first line is `Plug 'fatih/vim-go'` but I get an error when I start Vim saying `E492: Not an editor command Plug 'fatih/vim-go'`

**Comment by fatih** [comment]
Hi @carlca 

Thanks for the suggestion. Unfortunately I'm not using Windows. Until someone with a good windows experience can add it, there is not much I can do. I'll leave it open so people can see it. Thanks.

**Comment by fatih** [comment]
Hi,

Unfortunately, I'm archiving this project and will no longer maintaining it. For more information, please read my blog post: [Taking an indefinite sabbatical from my projects.](https://arslan.io/2018/10/09/taking-an-indefinite-sabbatical-from-my-projects/)

Thanks for the feedback and contribution.
