### ISSUE TITLE
Filetype not being correctly loaded on Windows

### ISSUE THREAD

**Issue by LukeMauldin** [fatih/vim-go-tutorial#32]
I am running Vim 8.0.311 on Windows 10.  I have filetype enabled in my .vimrc
`filetype plugin on`
If I do `:filetype?` then Vim reports `go`.  However, it looks like the contents of ftplugin\go.vim are not being loaded because the `setlocal omnifunc` isn't being set and other mappings like `gd` aren't being set.

**Comment by LukeMauldin** [comment]
As some more information, if I do `:scriptnames`, it shows the ftplugin\go.vim as loaded.  I removed the go.vim files from my VIM runtime files and then it works as expected with the file type being loaded, etc..

**Comment by fatih** [comment]
Hi,

Unfortunately, I'm archiving this project and will no longer maintaining it. For more information, please read my blog post: [Taking an indefinite sabbatical from my projects.](https://arslan.io/2018/10/09/taking-an-indefinite-sabbatical-from-my-projects/)

Thanks for the feedback and contribution.
