### ISSUE TITLE
Jump to result when using :GoReferrers and :GoDescribe

### ISSUE THREAD

**Issue by leksito** [fatih/vim-go-tutorial#36]
> Put your cursor on top of the handler and call :GoReferrers. This calls the referrers mode of vim-go, which finds references to the selected identifier, scanning all necessary packages within the workspace. The result will be a quickfix list, so you should be able to jump to the results easily.

How to jump to the result? I use 'Enter', but nothing happens. There is error "E553: No more items
" in statusbar. I tried find an answer in google but did not find anything.

**Comment by fatih** [comment]
You have to use :cn, :cp or :cc. There are many other commands as well and they are all part of the native quickfix feature. Call `:help quickfix` for more info
