### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by hnakamur** [fatih/vim-go-tutorial#38]
First of all, thanks for writing a great tutorial for vim-go!

Could you give me permission to translate this tutorial to Japanese?
Actually I've done translating 60% of it in my local machine.

If yes, when I finish the translation, can I send it as a pull request to this repository?
Or do you prefer the Japanese translation belong to my fork of this repository?

**Comment by fatih** [comment]
Hi @hnakamur 

Thanks a lot! I'm totally ok if you want to translate this to Japanese. I love Japan and the people there :) It would make me really happy. I don't think you need to send a Pull Request. However please rename the repo to `vim-go-tutorial-jp` as I think it's much more better.  So it can live under your name. When you finish it let me know on Twitter: https://twitter.com/fatih and I'll retweet it 👍
