### ISSUE TITLE
Case type setting

### ISSUE THREAD

**Issue by zhangyuheng** [fatih/vim-go-tutorial#39]
After a step-by-step practice, I think the [document](https://github.com/fatih/vim-go-tutorial/blob/master/README.md#vimrc-improvements-3) here should be written like this

```vim
let g:go_addtags_transform = 'camelcase'
```

rather than 

```vim
let g:go_snippet_case_type = "camelcase"
```

code example

```go
type foo struct {
	ServerName string `json:"serverName"`
}
```

It's a great tutorial and please forgive me if i am wrong.

**Comment by fatih** [comment]
You're right @zhangyuheng. Can you send a PR?

**Comment by zhangyuheng** [comment]
I sent a pull request.
