### ISSUE TITLE
snippet section:  expand panic after typing errp does not work nor does the section on fn,ff,ln,lf

### ISSUE THREAD

**Issue by phcurtis** [fatih/vim-go-tutorial#47]
the following does not work when working through Tutorial for vim-go  examples under the snippet section:  expand panic after typing errp does not work nor does the section on fn,ff,ln,lf ... the json hit tab does work

Snippet:
....

Let's put our cursor just after the newFoo() expression. Let's panic here if the err is non-nil. Type errp in insert mode and just hit tab. You'll see that it'll be expanded and put your cursor inside the panic()` function:

if err != nil {
    panic( )
          ^
          cursor position
}

It does not expand

I get this

19 func main() {
 20     res, err := newFoo()errp
 21
 22     our, err := json.Marshal(res)
 23 }

**Comment by nold2** [comment]
After add this code to your vimrc
```
Plug 'AndrewRadev/splitjoin.vim'
Plug 'SirVer/ultisnips'
```

try running this code on your vim editor 
`:source ~/.vimrc`
then do a 
`:PlugInstall`

**Comment by fatih** [comment]
Hi,

Unfortunately, I'm archiving this project and will no longer maintaining it. For more information, please read my blog post: [Taking an indefinite sabbatical from my projects.](https://arslan.io/2018/10/09/taking-an-indefinite-sabbatical-from-my-projects/)

Thanks for the feedback and contribution.
