### ISSUE TITLE
:GoMetaLinter does Not call 'go vet'

### ISSUE THREAD

**Issue by phcurtis** [fatih/vim-go-tutorial#48]
even if add to .vimrc:
let g:go_metalinter_enabled = ['vet','golint', 'errcheck']

**Comment by dreamer-nitj** [comment]
what is the output of explicit invocation of `:GoVet` on your go file? does it pass or does it report any errors?

**Comment by fatih** [comment]
Please open this issue to https://github.com/fatih/vim-go. This repo is only about the tutorial. Thanks.
