### ISSUE TITLE
GoCoverage not Highlighting anything

### ISSUE THREAD

**Issue by tommyknows** [fatih/vim-go-tutorial#56]
Hi,
I'm having a weird issue with the vim-go plugin. 
I started this tutorial and executed the `:GoCoverage` command - as it should be, some parts were highlighted green, others red. I then turned it off again, wrote the rest of the code and executed `:GoCoverage` again. 
This time, it didn't highlight anything, but colored the whole file like it was a comment. 
I am not able to get it being green and red again, I can just turn the Coverage off again and it's back to normal syntax highlighting.

Any idea on how I can debug this further?
I already tried re-opening vim and also executed `go test -coverprofile tempfile`, this seems to work just fine (Opened the browser and checked the highlighting).

Thanks

**Comment by fatih** [comment]
Can you please open your issue to the vim-go repo. This is just for the tutorial. There is nothing wrong with :GoCoverage. It must be a glitch. Thanks
