### ISSUE TITLE
`go get github.com/fatih/vim-go-tutorial` doesn't work.

### ISSUE THREAD

**Issue by dmikalova** [fatih/vim-go-tutorial#6]
Running `go get github.com/fatih/vim-go-tutorial` gives a "no buildable Go source files" error.

**Comment by deepthawtz** [comment]
I think the purpose of running that command is to create a scratch space for following along w/ the tutorial, you'll be the one adding Go code in that directory

**Comment by fatih** [comment]
@dmikalova yes as @deepthawtz said that's the case for it. I think we can rephrase it better in the tutorial :)

**Comment by deepthawtz** [comment]
@fatih yo, thanks for putting this tutorial together. Have been enjoying & using vim-go for a while and never knew many of these features existed. I think `:GoCoverage` just blew my mind

**Comment by dmikalova** [comment]
@deepthawtz Yup, I just cloned the repo and have been working through it. However, the tutorial says the following which doesn't work:

> If you already have a GOPATH set up just execute:
> go get github.com/fatih/vim-go-tutorial

Adding any go file should work, I just don't know how @fatih would want to handle it.

**Comment by fatih** [comment]
Actually there is only one example that requires a `GOPATH`. But having it inside a `GOPATH` from the beginning is future proof and thus better looking forward. I'll add a file as it seems to be better.

**Comment by InvisibleTech** [comment]
@fatih 
I am running this on OSX 10.11.6

I am still seeing this issue today.  Just started working the vim-go tutorial.

I have a path set up for my user:

`$HOME/golang/work/src/github.com/fatih/vim-go-tutorial
`
As shown by this grep out:

```
set | grep GO
GOPATH=/Users/mylogin/golang/work
GOROOT=/usr/local/opt/go/libexec
```

I follow my understanding of the tutorial:

> For the tutorial, all our examples will be under GOPATH/src/github.com/fatih/vim-go-tutorial/. Please be sure you're inside this folder. Create if necessary. This will make it easy to follow the tutorial.

So I go there as shown by this pwd out:

```
pwd
/Users/mylogin/golang/work/src/github.com/fatih/vim-go-tutorial
```

I run the command and get the error as shown here:

```
go get github.com/fatih/vim-go-tutorial
can't load package: package github.com/fatih/vim-go-tutorial: no buildable Go source files in /Users/mylogin/golang/work/src/github.com/fatih/vim-go-tutorial
```

I had go installed by Homebrew before starting this tutorial.  Could that be a source of problems?

**Comment by fatih** [comment]
@InvisibleTech 

I think it errors because the folder is already there. If you delete `vim-go-tutorial` and and do another `go get` it'll download it. But it's ok if it's there, just continue following the tutorial :)

**Comment by InvisibleTech** [comment]
That did work for me.  I had manually created the folder before running the go get command because I interpreted "Create if necessary." as immediate from the tutorial text copied below:

> For the tutorial, all our examples will be under GOPATH/src/github.com/fatih/vim-go-tutorial/. Please be sure you're inside this folder. Create if necessary. This will make it easy to follow the tutorial.

I was in follow-the-steps mode.

**Comment by fatih** [comment]
@InvisibleTech good catch, let me fix the wordings as they both contradict with each other.

**Comment by fatih** [comment]
@InvisibleTech I've updated the tutorial, thanks for the feedback.

**Comment by InvisibleTech** [comment]
Crap I just submitted a PR for that just now.  No wonder my fresh clone PR got merge conflict warnings.  Well whatever commit is best....
