### ISSUE TITLE
Required to update vim though vim is latest version

### ISSUE THREAD

**Issue by chengyuliu-cs** [fatih/vim-go-tutorial#61]
brew upgrade vim
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/versions).
No changes to formulae.

Error: vim 8.0.1553_1 already installed
bash-3.2$ vim golang.go 
vim-go requires Vim 7.4.1689 or Neovim, but you're using an older version.
Please update your Vim for the best vim-go experience.
If you really want to continue you can set this to make the error go away:
    let g:go_version_warning = 0
Note that some features may error out or behave incorrectly.
Please do not report bugs unless you're using Vim 7.4.1689 or newer.

**Comment by fatih** [comment]
Can you please open this issue to `vim-go` repo. This repo is only for the tutorial. Thanks
