### ISSUE TITLE
I can't see what is described

### ISSUE THREAD

**Issue by dubyte** [fatih/vim-go-tutorial#65]
In the section Beautify the next line can be found:

"You'll see that it's gray, thus it's not valid. Prepend + to the build word and save it again:"

but **I can't see it gray,** it was until later that I activate the molokai, that I see it as gray. I am wondering if the theme part should be move a little up.

**Comment by fatih** [comment]
Hi @dubyte 

What do you mean by theme part? Maybe adding a line, saying "throughout the tutorial, the colors and descriptions are made for the color scheme molokai. It might be different if you use a different color scheme" ?

**Comment by dubyte** [comment]
Hello Fatih:
I think the addition you mention is a good idea.

**Long explanation:**
`let g:go_highlight_build_constraints = 1`
When I activate that, the description of grey and how it changed only make sense if I have:
`colorscheme molokai`
so the comment you said sounds great :D
