### ISSUE TITLE
A query about certain symbol visible in vimgo environment.

### ISSUE THREAD

**Issue by lalat-das** [fatih/vim-go-tutorial#66]
This is not an issue exactly rather a question. Not sure if it related to vim-go environment also, suspecting it so as I have never seen it in case of vim.

1 > I am seeing +, ~, -, _  symbols just beside the line number in vim-go environment. 
Do they mean something.
I tried searching in vim-go doc but unable to find any clue.

2> Secondly I am unable to copy using Shift + Insert after highlighting a piece of code using mouse pointer. Which works on console though. I am using vim-go in a screen environment via putty. 

Kindly let me know if I am missing something obvious.

**Comment by fatih** [comment]
These are all vim related issue. The first one is a plugin that is not vim-go related. The second one depends on your Vim and OS setup. Please search stackoverflow for these kind of questions. Thanks
