### ISSUE TITLE
map <c-m> remaps <CR> in vim

### ISSUE THREAD

**Issue by tmc** [fatih/vim-go-tutorial#69]
`map <C-m> :cprevious<CR>`

this breaks hitting enter in a command line buffer:
`E11: Invalid in command-line window; <CR> executes, CTRL-C quits`

verbose map <CR>:
`   <CR>          :cprevious<CR>`

<C-p> is probably more appropriate.

**Comment by fatih** [comment]
Hi,

Unfortunately, I'm archiving this project and will no longer maintaining it. For more information, please read my blog post: [Taking an indefinite sabbatical from my projects.](https://arslan.io/2018/10/09/taking-an-indefinite-sabbatical-from-my-projects/)

Thanks for the feedback and contribution.
