### ISSUE TITLE
YouCompleteMe (code completion + snippets setup)

### ISSUE THREAD

**Issue by einthusan** [fatih/vim-go-tutorial#7]
I have always had issues with YouCompleteMe + any snippet plugin .. Can you talk about your setup on how you manage to achieve code completion.. since vim-go has built-in support for this, I would love to see it here.

**Comment by fatih** [comment]
Hi @einthusan. YCM is not supported by vim-go. But you're right about adding information regarding a completion system. I'll do it, let's keep this PR open until it's being added to the tutorial.

**Comment by einthusan** [comment]
@fatih sounds good. Awesome work on vim-go.

**Comment by einthusan** [comment]
@fatih any ETD for this? A lot of new comers to go will be relying on vim-go and the first thing that they need is a autocomplete. It would be really helpful for them. I know your super busy but just a friendly reminder.

**Comment by fatih** [comment]
@einthusan no. I have a family, I have a job, I have tons of other open source projects. I've created this from my spare times. I'll add when I have time. Meanwhile this repo is open, anyone can contribute.

**Comment by einthusan** [comment]
@fatih didn't mean to offend you.

**Comment by n10v** [comment]
I use [supertab](https://github.com/ervandew/supertab) and it works perfectly for me

**Comment by faraazkhan** [comment]
FWIW, I use YCM and UltiSnips with vim-go and it seems to be working ok. But YCM does package gocode and godef on its own (even if you install without --go-completer), so I see two copies of gocode running, which is not ideal, but autocompletion itself seems to work out of the box (along with snippets)

**Comment by ghost** [comment]
What about to check [this](https://stackoverflow.com/a/22253548/9304999). For me, it is working well.

**Comment by fatih** [comment]
Hi,

Unfortunately, I'm archiving this project and will no longer maintaining it. For more information, please read my blog post: [Taking an indefinite sabbatical from my projects.](https://arslan.io/2018/10/09/taking-an-indefinite-sabbatical-from-my-projects/)

Thanks for the feedback and contribution.
