### ISSUE TITLE
Missing information on HTML template

### ISSUE THREAD

**Issue by aitva** [fatih/vim-go-tutorial#70]
I spent a few month using vim-go without syntax highlighting for Go HTML template. I did not find documentation on the subject and I was using the `.gohtml`  extension for my templates.

Today, I had a look at `/ftdetect/gofiletype.vim` and found the `gohtmltmpl` file type. I've just enabled it for `.gohtml` and I am very happy to have syntax highlighting in vim!

Maybe it is worth mentioning in the tutorial?

**Comment by fatih** [comment]
@aitva sure! Mind opening a PR, I'm happy to merge it. Also it would be nice to add this information to `vim-go` itself documentation.

**Comment by fatih** [comment]
Hi,

Unfortunately, I'm archiving this project and will no longer maintaining it. For more information, please read my blog post: [Taking an indefinite sabbatical from my projects.](https://arslan.io/2018/10/09/taking-an-indefinite-sabbatical-from-my-projects/)

Thanks for the feedback and contribution.
